        </div>
        <div style="background-color:#757575; color:#ffffff; padding:20px; text-align:center;">
            <p style="font-size: 16px;  color:white; font-weight:300;width:90%; margin:20px auto;"> WIDIVES è la piattaforma per trovare e condividere siti di immersione</p>
        </div>
    </div>
    <p style="text-align:center; font-size: 12px; color:#8E8E8E"> Copyright © 2016 Wedives, Tutti i diritti sono riservati. </p>
</div>
</body>
</html>