    </div>
    <div style="background-color:#000000; color:#ffffff; padding:50px; text-align:center;">
        <p style="font-size: 14px;  color:white; font-weight:300;width:90%; margin:20px auto;"> Wedives è la piattaforma per trovare e condividere siti di immersione</p>
    </div>
    </div>

        <p style="text-align:center; font-size: 10px; color:#8E8E8E"> Copyright © 2016 Wedives, Tutti i diritti sono riservati. </p>
    </div>
</body>
</html>