<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Internal_email-29</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<body style="margin:0; padding:0;" background-color="#EDF1F3;">
<div style="width:700px; margin:50px auto; font-family: Roboto-Light, Arial, Helvetica, sans-serif; ">
    <div style="background: #FFFFFF; box-shadow: 1px 3px 9px 0px rgba(0,0,0,0.14); -webkit-box-shadow:1px 3px 9px 0px rgba(0,0,0,0.14); -moz-box-shadow: 1px 3px 9px 0px rgba(0,0,0,0.14); margin-bottom:30px;">
        <div style="height: 120px; background-color: #2196F3;">
            <h1 style="padding-top:50px; text-align: center; text-align: center; font-size: 2em; font-weight: 400; line-height: 30px; letter-spacing: 2px; margin: 0; color: #ffffff;">Wedives</h1>
        </div>
        <div style="padding: 16px;">