<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'ZF\Apigility\Provider',
        'ZF\ApiProblem',
        'ZF\MvcAuth',
        'ZF\OAuth2',
        'ZF\Hal',
        'ZF\ContentNegotiation',
        'ZF\ContentValidation',
        'ZF\Rest',
        'ZF\Rpc',
        'ZF\Versioning',
        'ZF\Configuration',
        'ImgMan\Apigility',
        'Matryoshka',
        'Matryoshka\Apigility',
        'Strapieno\User\Model',
        'Strapieno\User\Api',
        'Strapieno\UserAvatar\Model',
        'Strapieno\UserAvatar\Api',
        'Strapieno\Auth\Model',
        'Strapieno\Auth\Api',
        'Strapieno\Identity\Api',
        'Strapieno\UserRecoverPassword\Api',
        'Strapieno\UserCheckIdentity\Api',
        'Strapieno\Place\Model',
        'Strapieno\Place\Api',
        'Strapieno\PlaceGallery\Model',
        'Strapieno\PlaceGallery\Api',
        'Application',
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php',
        ),
    ),
);
