<?php /** @var $user \Strapieno\User\Model\Entity\UserInterface */ ?>
<?= $this->partial('email/layout/header'); ?>
<p>
    Hai dimenticato la tua password su WEDIVES.
</p>
<p>
    Per reimpostare la tua password <a style="text-decoration: none; color:#FFC107;" href="<?= $this->url('client/reset-password', ['token' => $user->getRecoverPasswordToken()]); ?>">clicca qui</a>.
</p>
<p>
    Buon Mare!
</p>
<?= $this->partial('email/layout/footer'); ?>
